PresentationLayer/Controllers/DeleteClassController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using BusinessLayer.Repositories;
using PresentationLayer.ViewModel;
using Microsoft.AspNetCore.Mvc;


namespace PresentationLayer.Controllers
{
    [Authorize]
    public class DeleteClassController : Controller
    {
        private readonly IClassRepository _classroomService;
        private readonly IClassroomUserRepository _classroomUserService;

        public DeleteClassController(IClassRepository classroomService, IClassroomUserRepository classroomUserRepository)
        {
            _classroomService = classroomService;
            _classroomUserService = classroomUserRepository;
        }

        public IActionResult Index(int id)
        {
            var classroom = _classroomService.GetRoomById(id);
            if (classroom == null)
            {
                return NotFound();
            }

            var viewModel = new ClassroomViewModel
            {
                Classroom = classroom
            };

            return View(viewModel);
        }

        [HttpPost]
        public IActionResult DeleteClass(int id)
        {
            if (id <= 0)
            {
                return BadRequest("Invalid classroom ID");
            }

            var classroom = _classroomService.GetRoomById(id);
            if (classroom == null)
            {
                return NotFound("Classroom not found");
            }

            var currentUserId = HttpContext.Session.GetString("UserId");

            if (currentUserId == null) {
                return View("~/Views/Home/Index.cshtml");
            }

             var classroomUser = _classroomUserService.GetClassroomUser(classroom.Id, Guid.Parse(currentUserId));
            if (classroomUser != null)
            {
                _classroomUserService.DeleteClassroomUser(classroomUser);
            }


            var remainingUsers = _classroomUserService.GetClassroomUsersByClassroomId(classroom.Id);
            if (!remainingUsers.Any())
            {
                _classroomService.DeleteRoom(id);
            }


            return RedirectToAction("Index", "Profile");
        }
    }
}

PresentationLayer/Views/DeleteClass/Index.cshtml
@model PresentationLayer.ViewModel.ClassroomViewModel
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Before Delete!";
}

<div class="mt-5">
    <div class="modal d-block position-static pt-2">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="text-danger">Warning</h5>
                </div>
                <div class="modal-body py-5">
                    <p class="fw-bold">
                        Do you really want to <mark>DELETE</mark> the classroom? You cannot undo this action.
                    </p>
                </div>
                <div class="modal-footer">
                    <a asp-controller="Profile" asp-action="Index" class="btn btn-secondary">Cancel</a>
                    <form asp-controller="DeleteClass" asp-action="DeleteClass" method="post">
                        <input type="hidden" name="id" value="@Model.Classroom.Id" />
                        <button type="submit" class="btn btn-danger">DELETE</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>