PresentationLayer/Components/NavbarViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;

public class NavbarViewComponent : ViewComponent
{
    private readonly IHttpContextAccessor _httpContextAccessor;

    public NavbarViewComponent(IHttpContextAccessor httpContextAccessor)
    {
        _httpContextAccessor = httpContextAccessor;
    }

    public IViewComponentResult Invoke()
    {
        var username = _httpContextAccessor.HttpContext.Session.GetString("Username");
        var role = _httpContextAccessor.HttpContext.Session.GetString("UserRole");
        return View("Default", (username, role));
    }
}

PresentationLayer/Views/Shared/_Footer.cshtml
<footer class="bg-primary text-light text-center py-4">
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <h5>Quick Links</h5>
                <ul class="list-unstyled">
                    <li><a href="/" class="text-light">Home</a></li>
                    <li><a href="#features" class="text-light">Features</a></li>
                    <li><a href="#contact" class="text-light">Contact</a></li>
                </ul>
            </div>

            <div class="col-md-4">
                <h5>Follow Us</h5>
                <a href="https://facebook.com" class="text-light me-2">
                    <i class="bi bi-facebook"></i>
                </a>
                <a href="https://twitter.com" class="text-light me-2">
                    <i class="bi bi-twitter"></i>
                </a>
                <a href="https://instagram.com" class="text-light">
                    <i class="bi bi-instagram"></i>
                </a>
            </div>

            <div class="col-md-4">
                <h5>StudyMate</h5>
                <p class="mb-0">&copy; @DateTime.Now.Year StudyMate. All rights reserved.</p>
            </div>
        </div>
    </div>
</footer>

PresentationLayer/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor HttpContextAccessor

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title - SkillMate</title>

    <style>
        body {
            padding-top: 56px;
        }
    </style>

    <link rel="stylesheet" href="~/lib/bootstrap/css/bootstrap.min.css" />
    <link rel="stylesheet" 
          href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css">
</head>
<body>
    @* view component: NavbarViewComponent *@
    @await Component.InvokeAsync("Navbar")

    <div class="container mt-4">
        @RenderBody()
    </div>

    <script src="~/lib/bootstrap/js/bootstrap.bundle.min.js"></script>
</body>

@* Partial view: _Footer.cshtml *@
@await Html.PartialAsync("_Footer")

</html>