PresentationLayer/Components/NavbarViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;

public class NavbarViewComponent : ViewComponent
{
    private readonly IHttpContextAccessor _httpContextAccessor;

    public NavbarViewComponent(IHttpContextAccessor httpContextAccessor)
    {
        _httpContextAccessor = httpContextAccessor;
    }

    public IViewComponentResult Invoke()
    {
        var username = _httpContextAccessor.HttpContext.Session.GetString("Username");
        var role = _httpContextAccessor.HttpContext.Session.GetString("UserRole");
        return View("Default", (username, role));
    }
}

PresentationLayer/Controllers/CreateController.cs
using Microsoft.AspNetCore.Mvc;
using BusinessLayer.Repositories;
using Microsoft.AspNetCore.Authorization;
using DataAccessLayer.Models;
using PresentationLayer.ViewModel;


namespace PresentationLayer.Controllers
{
    [Authorize]
    public class CreateController : Controller
    {
        private readonly IClassRepository _roomsRepository;
        private readonly IClassroomUserRepository _classroomUserService;

        public CreateController(IClassRepository roomsRepository, IClassroomUserRepository classroomUserRepository)
        {
            _roomsRepository = roomsRepository;
            _classroomUserService = classroomUserRepository;
        }

        public ViewResult Index()
        {
            var userId = HttpContext.Session.GetString("UserId");

            if (userId == null) {
                return View("~/Views/Home/Index.cshtml");
            }

            ClassroomViewModel classroomViewModel = new ClassroomViewModel()
            {
                UserId = Guid.Parse(userId),
                Rooms = _roomsRepository.GetAllRooms(),
            };
            return View(classroomViewModel);
        }

        [HttpPost]
        public IActionResult CreateClass(string classname, string classtype) 
        {
            if (string.IsNullOrWhiteSpace(classname) || string.IsNullOrWhiteSpace(classtype))
            {
                return BadRequest("Class name and type cannot be empty.");
            }

            var userId = HttpContext.Session.GetString("UserId");

            if (userId == null)
            {
                return Unauthorized("You must be logged in to create a class.");
            }

            var newClassroom = new Classroom
            {
                ClassName = classname,
                Type = classtype,
            };
            _roomsRepository.AddRoom(newClassroom);

             var classroomUser = new ClassroomUser
            {
                ClassroomId = newClassroom.Id,
                UserId = Guid.Parse(userId)
            };
            _classroomUserService.AddClassroomUser(classroomUser);

            return RedirectToAction("Index", "Classroom");
        }

    }
}

PresentationLayer/Controllers/ProfileController.cs
using BusinessLayer.Repositories;
using PresentationLayer.ViewModel;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;

namespace PresentationLayer.Controllers
{
    [Authorize]
    public class ProfileController : Controller
    {
        private readonly IClassRepository _roomsRepository;

        public ProfileController(IClassRepository roomsRepository)
        {
            _roomsRepository = roomsRepository;
        }

        public ViewResult Index()
        {
            var userId = HttpContext.Session.GetString("UserId");

            if (userId == null)
            {
                return View("~/Views/Home/Index.cshtml");
            }

            Guid parsedUserId = Guid.Parse(userId);

            var joinedRooms = _roomsRepository.GetUserClassrooms(parsedUserId);

            ClassroomViewModel classroomViewModel = new ClassroomViewModel()
            {
                UserId = parsedUserId,
                Rooms = joinedRooms,
            };

            return View(classroomViewModel);
        }
    }
}

PresentationLayer/Views/Shared/Components/Navbar/Default.cshtml
@model (string Username, string Role)

<nav class="navbar navbar-expand-lg navbar-dark bg-primary fixed-top">
    <div class="container">
        <a class="navbar-brand" asp-controller="Home" asp-action="Index">SkillMate</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ms-auto">
                @if (!string.IsNullOrEmpty(Model.Username))
                {
                    <li class="nav-item">
                        <a asp-controller="Profile" asp-action="Index" class="nav-link">Profile (@Model.Username)</a>
                    </li>
                    @if (Model.Role == "Admin")
                    {
                        <li class="nav-item">
                            <a asp-controller="Admin" asp-action="Dashboard" class="nav-link">Admin Dashboard</a>
                        </li>
                    }
                    <li class="nav-item">
                        <form asp-controller="Login" asp-action="Logout" method="post" class="d-inline">
                            <button type="submit" class="btn btn-link nav-link">Logout</button>
                        </form>
                    </li>
                }
                else
                {
                    <li class="nav-item">
                        <a asp-controller="Login" asp-action="Index" class="nav-link">Login</a>
                    </li>
                }
            </ul>
        </div>
    </div>
</nav>


<nav class="navbar navbar-expand-lg navbar-dark bg-primary fixed-top">
        <div class="container">
            <a class="navbar-brand" asp-controller="Home" asp-action="Index">SkillMate</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ms-auto">
                    @if (!string.IsNullOrEmpty(Model.Username))
                    {
                        <li class="nav-item">
                            <a asp-controller="Classroom" asp-action="Index" class="nav-link @(ViewBag.Title == "Classroom" ? "active" : "")">Classroom</a>
                        </li>
                        <li class="nav-item">
                            <a asp-controller="Create" asp-action="Index" class="nav-link @(ViewBag.Title == "Create" ? "active" : "")">Create</a>
                        </li>
                        <li class="nav-item">
                            <a asp-controller="Profile" asp-action="Index" class="nav-link">Profile (@Model.Username)</a>
                        </li>
                        @if (Model.Role == "Admin")
                        {
                            <li class="nav-item">
                                <a asp-controller="Admin" asp-action="Dashboard" class="nav-link">Admin Dashboard</a>
                            </li>
                        }
                        <li class="nav-item">
                            <form asp-controller="Login" asp-action="Logout" method="post" class="d-inline">
                                <button type="submit" class="btn btn-link nav-link">Logout</button>
                            </form>
                        </li>
                    }
                    else
                    {
                        <li class="nav-item">
                            <a asp-controller="Login" asp-action="Index" class="nav-link">Login</a>
                        </li>
                    }
                </ul>
            </div>
        </div>
    </nav>